# config.yml

entra_id:
  tenant_id:     "787e711e-1364-4fdc-ba66-b046d0459878"
  client_id:     "53c53e6d-7ed0-4bf2-b853-1b8cb7a51ea5"
  client_secret: "2rx8Q~x_cEprC5cfhhq0lOhRuMYiZtWQoJyxsc8s"
  domain:        "marwanhamdaoui2020gmail.onmicrosoft.com"
  poll_interval: 60

redis:
  host: "localhost"
  port: 6379

vms:
  - name:     "AliceVm"
    ip:       "10.0.0.5"
    username: "AliceVm"
    password: "L@b-passw0rd_2026"

  # Add new VM here:
  # - name:     "vm-3"
  #   ip:       "10.0.1.6"
  #   username: "marwan"
  #   password: "LabP@ssw0rd2026!"

buffer:
  max_size: 1000

scoring:
  warmup_hours:     0.03
  action_after_mins: 1
  alert_threshold:   0.50
  mfa_threshold:     0.70
  block_threshold:   0.85

actions:
  noc_webhook: "https://your-webhook-url"
  block_users: true
  force_mfa:   true
